### ISSUE TITLE
Auto complete function annotation

### ISSUE THREAD

**Issue by NaakkaDev** [EmmyLuaLs/Zed-EmmyLua#3]
Would it be possible to add automatic annotations when typing `---`, like with the VS Code sumneko plugin?

https://github.com/user-attachments/assets/7f8ef39e-00b2-4ecd-861f-4f730cf946c0

**Comment by CppCXY** [comment]
we need type '@' :

<img width="819" height="424" alt="Image" src="https://github.com/user-attachments/assets/04f3cea7-6cae-40a4-b37b-47bc8bd67fe8" />

**Comment by NaakkaDev** [comment]
Yes, I noticed that, but that is different from what I meant. I would like the auto-completion to look at the below function and automatically add all the annotation fields with a single click. This would significantly speed up writing annotations, at least for me.

Example:
https://github.com/user-attachments/assets/4e52ea99-98cc-4f95-8cc9-80432040e64e

**Comment by CppCXY** [comment]
I can not see what you want to display 

<img width="994" height="643" alt="Image" src="https://github.com/user-attachments/assets/5bff5c58-8160-435a-a95e-61b01846eea5" />

**Comment by NaakkaDev** [comment]
I hope this gif works.
![Image](https://github.com/user-attachments/assets/3f5bab5a-d133-4dc6-873e-99ea68d26849)

Basically same as this: https://github.com/LuaLS/lua-language-server/wiki/Annotations#tips

**Comment by CppCXY** [comment]
For modern AI, complex snippet features aren't that important anymore—especially now that AI has next-edit capability. I implemented this feature before, but after several rounds of refactoring I found it wasn't very useful and didn't continue it.
<img width="603" height="351" alt="Image" src="https://github.com/user-attachments/assets/cf6d322b-cbff-4677-9eb9-9837f2883ac4" />

**Comment by NaakkaDev** [comment]
Oh that's a shame. I have AI fully disabled.

**Comment by CppCXY** [comment]
In the current Zed plugin, some parts — including doc highlighting — are done directly by AI. AI truly frees up productivity; for example, [this project](https://github.com/CppCXY/lua-rs) was entirely written by AI.

**Comment by aridclown** [comment]
> Oh that's a shame. I have AI fully disabled.

I agree with @NaakkaDev. While AI completions are the new norm for most people, there's still a handful of devs (myself included) who don't utilize them sometimes (e.g., when learning a new language/framework, I mostly rely on the IDE's capabilities).

While I agree that this is not a high-priority QOL issue, I still see value in providing autocomplete, just as LuaLS does.

**Comment by CppCXY** [comment]
https://github.com/EmmyLuaLs/emmylua-analyzer-rust/commit/9f3f60b4ff47357b7a02debec154c987d06390f8
